# Generated by Django 4.1.2 on 2022-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('header', models.CharField(default=None, max_length=200, null=True)),
                ('comment', models.CharField(default=None, max_length=300, null=True)),
            ],
        ),
    ]
