# Generated by Django 6.0.4 on 2026-04-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel',
        ),
    ]
