# Generated by Django 6.0.4 on 2026-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Kichik sarlavha')),
                ('label', models.CharField(max_length=100, verbose_name="Yorliq (masalan: Kelajak ta'limi)")),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Rasm')),
                ('button_text', models.CharField(default='Boshlash', max_length=50, verbose_name='Tugma matni')),
                ('button_url', models.CharField(default='#test-selection', max_length=200, verbose_name='Tugma havolasi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi')),
            ],
            options={
                'verbose_name': 'Karusel',
                'verbose_name_plural': 'Karusellar',
                'ordering': ['order'],
            },
        ),
    ]
