# Generated by Django 6.0.4 on 2026-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='button_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tugma havolasi'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Yorliq (masalan: Kelajak ta'limi)"),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kichik sarlavha'),
        ),
    ]
